name: Test Autograde
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  autograde:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: src/package-lock.json
      - name: install dependencies
        run: npm install
      - name : Autograde Testing
        run: npm run test -- --verbose 2>&1 | tee test.log≥
      - name : Show log file
        run: cat test.log
      - uses: masaditya/test-autograde@v10.0